[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "SignalF"
authors = [{name = "Olaf Meyer", email = "signalf@scotec-software.com"}]
dynamic = ["version", "description"]
